"""empty message

Revision ID: 80ee8bcd6c05
Revises: da34323e55c4
Create Date: 2018-12-27 20:18:59.680855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ee8bcd6c05'
down_revision = 'da34323e55c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feature_request', sa.Column('is_archived', sa.Boolean(), nullable=True))
    op.add_column('feature_request', sa.Column('last_update', sa.DateTime(), nullable=False))
    op.drop_constraint('feature_request_title_key', 'feature_request', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('feature_request_title_key', 'feature_request', ['title'])
    op.drop_column('feature_request', 'last_update')
    op.drop_column('feature_request', 'is_archived')
    # ### end Alembic commands ###
